/*
 * AnaisGui.java
 *
 * Created on 9 ao�t 2005, 09:41
 */
package anais.historical;
import java.awt.*;
import javax.swing.*;

import anais.gene.*;
import anais.historical.WorldDarwinPrime;

import java.io.Serializable;
/**
 * @author  Jaspart
 */
public class Gui extends javax.swing.JFrame implements Serializable {

	private static final long serialVersionUID = -554181590097559725L;
/**
 * paint method in your own class that extends Canvas
 *
 * @param g where to paint e.g. printer, screen, RAM
 */

    BackusNaur BNFMap;

    /** Creates new form NewJFrame */
    public Gui() {
        BNFMap=new BackusNaur();
        initComponents();
        this.setFont(new java.awt.Font("Arial", 0, 8));
        JFrame.setDefaultLookAndFeelDecorated(false);
        this.setBounds(30, 50, 800, 600);
    }
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
	private void initComponents() {
    	
    	/** 
    	 * Main Window Setting 
    	 * */
        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("YNhôt System");
        setName("MainWindow"); // NOI18N
        getContentPane().setLayout(null);
        
        /** 
         * Main Containers 
         * */
        
        /* ProgressBar */
        ProgressBar = new javax.swing.JProgressBar();
        getContentPane().add(ProgressBar);
        ProgressBar.setBounds(20, 510, 460, 20);
        
        /* GoButton */
        GoButton = new javax.swing.JButton();
        GoButton.setText("Go !");
        GoButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                GoButtonActionPerformed(evt);
            }
        });
        getContentPane().add(GoButton);
        GoButton.setBounds(530, 500, 70, 30);

        /* ExitButton */
        ExitButton = new javax.swing.JToggleButton();
        ExitButton.setText("Exit");
        ExitButton.setActionCommand("OK");
        ExitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitButtonActionPerformed(evt);
            }
        });
        getContentPane().add(ExitButton);
        ExitButton.setBounds(610, 500, 80, 30);
        
        /** 
         * Menu Declaration 
         * */
        
        MenuBar = new javax.swing.JMenuBar();{
	        MenuFile = new javax.swing.JMenu();{
	        	
	        	/* Menu File */
	            MenuFile.setText("File");
	            MenuFile.addItemListener(new java.awt.event.ItemListener() {
	                public void itemStateChanged(java.awt.event.ItemEvent evt) {
	                    menuFileItemStateChanged(evt);
	                }
	            });
	            
	            /* Menu File/Open */
	            FileOpenChooser = new javax.swing.JFileChooser();
		        FileOpenChooser.setPreferredSize(new java.awt.Dimension(800, 600));
	            FileOpen = new javax.swing.JFrame();
		        FileOpen.setTitle("Open");
		        FileOpen.getContentPane().setLayout(new java.awt.BorderLayout(500, 500));
		        FileOpen.getContentPane().add(FileOpenChooser, java.awt.BorderLayout.CENTER);
		        Open = new javax.swing.JMenuItem();
		        Open.setText("Open");
		        Open.addActionListener(new java.awt.event.ActionListener() {
		            public void actionPerformed(java.awt.event.ActionEvent evt) {
		                fileOpenActionPerformed(evt);
		            }
		        });
		        MenuFile.add(Open);
		        
		        /* Menu File/Save */
		        Save = new javax.swing.JMenuItem();
		        Save.setText("Save");
		        Save.addActionListener(new java.awt.event.ActionListener() {
		            public void actionPerformed(java.awt.event.ActionEvent evt) {
		                fileSaveActionPerformed(evt);
		            }
		        });
		        MenuFile.add(Save);
		        
		        /* Menu File/SaveAs */
	            FileChooserSaveAs = new javax.swing.JFileChooser();
		        FileChooserSaveAs.setAutoscrolls(true);
		        FileChooserSaveAs.setDragEnabled(true);
		        FileChooserSaveAs.setOpaque(true);
	            FileSaveAs = new javax.swing.JFrame();
		        FileSaveAs.setTitle("Save as...");
		        FileSaveAs.getContentPane().setLayout(new java.awt.BorderLayout(500, 500));
		        FileSaveAs.getContentPane().add(FileChooserSaveAs, java.awt.BorderLayout.CENTER);
		        SaveAs = new javax.swing.JMenuItem();
		        SaveAs.setText("Save as...");
		        SaveAs.addActionListener(new java.awt.event.ActionListener() {
		            public void actionPerformed(java.awt.event.ActionEvent evt) {
		                fileSaveAsActionPerformed(evt);
		            }
		        });
		        MenuFile.add(SaveAs);
		        
		        /* Menu File/Close */
	            FileClose = new javax.swing.JFrame();
		        FileClose.setTitle("Close");
		        FileClose.getContentPane().setLayout(new anais.gui.AbsoluteLayout());
		        CloseButton = new javax.swing.JButton();
		        CloseButton.setText("Close");
		        FileClose.getContentPane().add(CloseButton, new anais.gui.AbsoluteConstraints(160, 340, -1, -1));
		        SaveButton = new javax.swing.JButton();
		        SaveButton.setText("Save");
		        FileClose.getContentPane().add(SaveButton, new anais.gui.AbsoluteConstraints(250, 340, -1, -1));
		        Close = new javax.swing.JMenuItem();
		        Close.setText("Close");
		        Close.addActionListener(new java.awt.event.ActionListener() {
		            public void actionPerformed(java.awt.event.ActionEvent evt) {
		                fileCloseActionPerformed(evt);
		            }
		        });
		        MenuFile.add(Close);
		        
		        /* Menu File/Publish */
		        Publish = new javax.swing.JMenuItem();
		        Publish.setText("Publish");
		        MenuFile.add(Publish);
		        
		        /* Cancel Button */
		        CancelButton = new javax.swing.JButton();
		        CancelButton.setText("Cancel");
		        CancelButton.addActionListener(new java.awt.event.ActionListener() {
		            public void actionPerformed(java.awt.event.ActionEvent evt) {
		                fileCancelButtonActionPerformed(evt);
		            }
		        });
		        FileClose.getContentPane().add(CancelButton, new anais.gui.AbsoluteConstraints(360, 340, -1, -1));
		        
		        MenuBar.add(MenuFile);
	        }
	        MenuNew = new javax.swing.JMenu();{
	        	/* Menu New */
	            MenuNew.setText("New");
	            MenuNew.addItemListener(new java.awt.event.ItemListener() {
	                public void itemStateChanged(java.awt.event.ItemEvent evt) {
	                    menuNewItemStateChanged(evt);
	                }
	            });
	            /* Menu New/PDE */
	        	NewPDE = new javax.swing.JFrame();
		        NewPDE.setTitle("Solve Partial Derivative Equations");
		        NewEDP = new javax.swing.JMenuItem();
	            NewEDP.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_E, java.awt.event.InputEvent.CTRL_MASK));
	            NewEDP.setText("Partial Derivative Equations");
	            MenuNew.add(NewEDP);
	            
	            /* Menu New/Optimisation */
	            NewOptimisation = new javax.swing.JFrame();
		        NewOptimisation.setTitle("Solve Optimisation Equation");
		        NewOpti = new javax.swing.JMenuItem();
		        NewOpti.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
		        NewOpti.setText("Optimisation Equation");
		        MenuNew.add(NewOpti);
		        
		        /* Menu New/Correlation */
	            NewCorrelation = new javax.swing.JFrame();
		        NewCorrelation.setTitle("Find Correlation Function");
		        NewCorre = new javax.swing.JMenuItem();
		        NewCorre.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_C, java.awt.event.InputEvent.CTRL_MASK));
		        NewCorre.setText("Correlation Function");
		        MenuNew.add(NewCorre);
		        MenuBar.add(MenuNew);
	        }
	        MenuParameter = new javax.swing.JMenu();{
	        	/* Menu Parameters */
		        MenuParameter.setText("Parameters");
		        
	        	/* Menu Parameters/Genetic */
		        ParamGene = new javax.swing.JMenuItem();
		        ParamGene.setText("Genetic");
	            ParameterGenetic = new javax.swing.JFrame();
		        ParameterGenetic.setTitle("Genetic");
		        MenuParameter.add(ParamGene);
		        
		        /* Menu Parameters/Population */
		        ParamPopu = new javax.swing.JMenuItem();
		        ParamPopu.setText("Population");
	            ParameterPopulation = new javax.swing.JFrame();
		        ParameterPopulation.setTitle("Population");
		        MenuParameter.add(ParamPopu);

		        MenuBar.add(MenuParameter);

	        }
	        MenuAbout = new javax.swing.JMenu();{
	        	/* Menu About */
		        MenuAbout.setText("About");

		        /* Menu About/Display */
	            AboutDisplay = new javax.swing.JFrame();
		        AboutDisplay.setTitle("Display");
	        	Display = new javax.swing.JMenuItem();
		        Display.setText("Display");
		        
		        /* Menu About/Help */
	            AboutHelp = new javax.swing.JFrame();
		        AboutHelp.setTitle("Help");
		        Help = new javax.swing.JMenuItem();
		        Help.setText("Help");
		        
		        /* Menu About/About */
	            AboutAbout = new javax.swing.JFrame();
		        AboutAbout.setTitle("About");
		        About = new javax.swing.JMenuItem();
		        About.setText("About");
		        MenuAbout.add(Display);
		        MenuAbout.add(Help);
		        About.addActionListener(new java.awt.event.ActionListener() {
		            public void actionPerformed(java.awt.event.ActionEvent evt) {
		                aboutAboutActionPerformed(evt);
		            }
		        });
		        MenuAbout.add(About);
		        MenuBar.add(MenuAbout);
	        }
	        setJMenuBar(MenuBar);
        }
        
        /** 
         * Button Declaration 
         * */
        
        /* VarCheckBox */
        VarCheckBox = setGeneCheckBox("<var>", new GeneVariable(), 20, 10, 110, 22);
        
        /* ExpOpCheckBox */
        ExpOpCheckBox = new javax.swing.JCheckBox();
        ExpOpCheckBox.setFont(new java.awt.Font("Courier New", 0, 10));
        ExpOpCheckBox.setText("<exp><op><exp>");
        getContentPane().add(ExpOpCheckBox);
        ExpOpCheckBox.setBounds(20, 30, 110, 22);

        /* PreOpCheckBox */
        PreOpCheckBox = new javax.swing.JCheckBox();
        PreOpCheckBox.setFont(new java.awt.Font("Courier New", 0, 10)); // NOI18N
        PreOpCheckBox.setText("<pre-op><exp>");
        PreOpCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PreOpCheckBoxActionPerformed(evt);
            }
        });
        getContentPane().add(PreOpCheckBox);
        PreOpCheckBox.setBounds(20, 50, 110, 22);

        /* VarOpCheckBox */
        VarOpCheckBox = new javax.swing.JCheckBox();
        VarOpCheckBox.setFont(new java.awt.Font("Courier New", 0, 10)); // NOI18N
        VarOpCheckBox.setText("<var><op><exp>");
        getContentPane().add(VarOpCheckBox);
        VarOpCheckBox.setBounds(20, 70, 110, 22);

        /* PreVarCheckBox */
        PreVarCheckBox = new javax.swing.JCheckBox();
        PreVarCheckBox.setFont(new java.awt.Font("Courier New", 0, 10)); // NOI18N
        PreVarCheckBox.setText("<pre-op><var>");
        getContentPane().add(PreVarCheckBox);
        PreVarCheckBox.setBounds(20, 90, 110, 22);

        /* PlusCheckBox */
        PlusCheckBox = new javax.swing.JCheckBox();
        PlusCheckBox.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        PlusCheckBox.setText("+");
        getContentPane().add(PlusCheckBox);
        PlusCheckBox.setBounds(130, 10, 40, 22);

        /* MinusCheckBox */
        MinusCheckBox = new javax.swing.JCheckBox();
        MinusCheckBox.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        MinusCheckBox.setText("-");
        getContentPane().add(MinusCheckBox);
        MinusCheckBox.setBounds(130, 30, 40, 22);

        /* MultiplyCheckBox */
        MultiplyCheckBox = new javax.swing.JCheckBox();
        MultiplyCheckBox.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        MultiplyCheckBox.setText("*");
        getContentPane().add(MultiplyCheckBox);
        MultiplyCheckBox.setBounds(130, 50, 40, 22);

        /* DivideCheckBox */
        DivideCheckBox = new javax.swing.JCheckBox();
        DivideCheckBox.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        DivideCheckBox.setText("/");
        getContentPane().add(DivideCheckBox);
        DivideCheckBox.setBounds(130, 70, 40, 22);

        /* PowerCheckBox */
        PowerCheckBox = new javax.swing.JCheckBox();
        PowerCheckBox.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        PowerCheckBox.setText("^");
        getContentPane().add(PowerCheckBox);
        PowerCheckBox.setBounds(130, 90, 40, 22);

        /* ExpCheckBox */
        ExpCheckBox = new javax.swing.JCheckBox();
        ExpCheckBox.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        ExpCheckBox.setText("exp");
        getContentPane().add(ExpCheckBox);
        ExpCheckBox.setBounds(170, 10, 60, 22);

        /* LogCheckBox */
        LogCheckBox = new javax.swing.JCheckBox();
        LogCheckBox.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        LogCheckBox.setText("ln");
        getContentPane().add(LogCheckBox);
        LogCheckBox.setBounds(170, 30, 60, 22);

        /* SinCheckBox */
        SinCheckBox = new javax.swing.JCheckBox();
        SinCheckBox.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        SinCheckBox.setText("sin");
        getContentPane().add(SinCheckBox);
        SinCheckBox.setBounds(170, 50, 60, 22);

        /* TanCheckBox */
        TanCheckBox = new javax.swing.JCheckBox();
        TanCheckBox.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        TanCheckBox.setText("tan");
        getContentPane().add(TanCheckBox);
        TanCheckBox.setBounds(170, 70, 60, 22);
        
        /* SqrtCheckBox */
        SqrtCheckBox = new javax.swing.JCheckBox();
        SqrtCheckBox.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        SqrtCheckBox.setText("sqrt");
        SqrtCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SqrtCheckBoxActionPerformed(evt);
            }
        });
        getContentPane().add(SqrtCheckBox);
        SqrtCheckBox.setBounds(170, 90, 60, 22);
        
        /* TenthCheckBox */
        TenthCheckBox = new javax.swing.JCheckBox();
        TenthCheckBox.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        TenthCheckBox.setText("0.1");
        getContentPane().add(TenthCheckBox);
        TenthCheckBox.setBounds(230, 10, 50, 22);

        /* OneCheckBox */
        OneCheckBox = new javax.swing.JCheckBox();
        OneCheckBox.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        OneCheckBox.setText("1");
        getContentPane().add(OneCheckBox);
        OneCheckBox.setBounds(230, 30, 40, 22);

        /* XCheckBox */
        XCheckBox = new javax.swing.JCheckBox();
        XCheckBox.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        XCheckBox.setText("x=");
        XCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                XCheckBoxActionPerformed(evt);
            }
        });
        getContentPane().add(XCheckBox);
        XCheckBox.setBounds(230, 50, 40, 22);
        XminTextField = new javax.swing.JTextField();
        XminTextField.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        getContentPane().add(XminTextField);
        XminTextField.setBounds(270, 50, 40, 24);
        XmaxTextField = new javax.swing.JTextField();
        XmaxTextField.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        getContentPane().add(XmaxTextField);
        XmaxTextField.setBounds(310, 50, 40, 24);

        /* YCheckBox */
        YCheckBox = new javax.swing.JCheckBox();
        YCheckBox.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        YCheckBox.setText("y=");
        getContentPane().add(YCheckBox);
        YCheckBox.setBounds(230, 70, 40, 22);
        YminTextField = new javax.swing.JTextField();
        YminTextField.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        getContentPane().add(YminTextField);
        YminTextField.setBounds(270, 70, 40, 24);
        YmaxTextField = new javax.swing.JTextField();
        YmaxTextField.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        getContentPane().add(YmaxTextField);
        YmaxTextField.setBounds(310, 70, 40, 24);
        
        /* ZCheckBox */
        ZCheckBox = new javax.swing.JCheckBox();
        ZCheckBox.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        ZCheckBox.setText("z=");
        getContentPane().add(ZCheckBox);
        ZCheckBox.setBounds(230, 90, 40, 22);
        ZminTextField = new javax.swing.JTextField();
        ZminTextField.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        getContentPane().add(ZminTextField);
        ZminTextField.setBounds(270, 90, 40, 24);
        ZmaxTextField = new javax.swing.JTextField();
        ZmaxTextField.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        getContentPane().add(ZmaxTextField);
        ZmaxTextField.setBounds(310, 90, 40, 24);
        
        /* ACheckBox */
        ACheckBox = new javax.swing.JCheckBox();
        ACheckBox.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        ACheckBox.setText("a");
        getContentPane().add(ACheckBox);
        ACheckBox.setBounds(370, 10, 40, 22);
        AvalTextField = new javax.swing.JTextField();
        AvalTextField.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        getContentPane().add(AvalTextField);
        AvalTextField.setBounds(410, 10, 40, 24);
        
        /* BCheckBox */
        BCheckBox = new javax.swing.JCheckBox();
        BCheckBox.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        BCheckBox.setText("b");
        getContentPane().add(BCheckBox);
        BCheckBox.setBounds(370, 30, 40, 22);
        BvalTextField = new javax.swing.JTextField();
        BvalTextField.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        getContentPane().add(BvalTextField);
        BvalTextField.setBounds(410, 30, 40, 24);
        
        /* CCheckBox */
        CCheckBox = new javax.swing.JCheckBox();
        CCheckBox.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        CCheckBox.setText("c");
        getContentPane().add(CCheckBox);
        CCheckBox.setBounds(370, 50, 40, 22);
        CvalTextField = new javax.swing.JTextField();
        CvalTextField.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        getContentPane().add(CvalTextField);
        CvalTextField.setBounds(410, 50, 40, 24);
        
        /* DCheckBox */
        DCheckBox = new javax.swing.JCheckBox();
        DCheckBox.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        DCheckBox.setText("d");
        getContentPane().add(DCheckBox);
        DCheckBox.setBounds(370, 70, 40, 22);
        DvalTextField = new javax.swing.JTextField();
        DvalTextField.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        getContentPane().add(DvalTextField);
        DvalTextField.setBounds(410, 70, 40, 24);
        
        /* ECheckBox */
        ECheckBox = new javax.swing.JCheckBox();
        ECheckBox.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        ECheckBox.setText("e");
        getContentPane().add(ECheckBox);
        ECheckBox.setBounds(370, 90, 40, 22);
        EvalTextField = new javax.swing.JTextField();
        EvalTextField.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        getContentPane().add(EvalTextField);
        EvalTextField.setBounds(410, 90, 40, 24);

        /* UnknownTable */
        UnknownTable = new javax.swing.JTable();
        UnknownTable.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        UnknownTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null}
            },
            new String [] {
                "Title 1"
            }
        ));
        getContentPane().add(UnknownTable);
        UnknownTable.setBounds(460, 20, 180, 90);

        /* AddButton */
        AddButton = new javax.swing.JButton();
        AddButton.setText("Add");
        getContentPane().add(AddButton);
        AddButton.setBounds(650, 20, 90, 27);

        /* DelButton */
        DelButton = new javax.swing.JButton();
        DelButton.setText("Delete");
        getContentPane().add(DelButton);
        DelButton.setBounds(650, 50, 90, 27);

        /* UnknownComboBox */
        UnknownComboBox = new javax.swing.JComboBox();
        UnknownComboBox.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        getContentPane().add(UnknownComboBox);
        UnknownComboBox.setBounds(650, 86, 90, 20);

        /* FunctionTextField */
        FunctionTextField = new javax.swing.JTextField();
        FunctionTextField.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        FunctionTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FunctionTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(FunctionTextField);
        FunctionTextField.setBounds(20, 120, 430, 170);

        /* ContraintTextField1 */
        ContraintTextField1 = new javax.swing.JTextField();
        ContraintTextField1.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        getContentPane().add(ContraintTextField1);
        ContraintTextField1.setBounds(460, 120, 240, 24);

        /* ContraintTextField2 */
        ContraintTextField2 = new javax.swing.JTextField();
        ContraintTextField2.setFont(new java.awt.Font("Courier New", 0, 12));
        getContentPane().add(ContraintTextField2);
        ContraintTextField2.setBounds(460, 140, 240, 24);

        /* DivideCheckBox */
        ContraintTextField3 = new javax.swing.JTextField();
        ContraintTextField3.setFont(new java.awt.Font("Courier New", 0, 12));
        getContentPane().add(ContraintTextField3);
        ContraintTextField3.setBounds(460, 160, 240, 24);

        /* ContraintTextField4 */
        ContraintTextField4 = new javax.swing.JTextField();
        ContraintTextField4.setFont(new java.awt.Font("Courier New", 0, 12));
        getContentPane().add(ContraintTextField4);
        ContraintTextField4.setBounds(460, 180, 240, 24);

        /* BoundTextField1 */
        BoundTextField1 = new javax.swing.JTextField();
        BoundTextField1.setFont(new java.awt.Font("Courier New", 0, 12));
        getContentPane().add(BoundTextField1);
        BoundTextField1.setBounds(460, 210, 240, 24);

        /* BoundTextField2 */
        BoundTextField2 = new javax.swing.JTextField();
        BoundTextField2.setFont(new java.awt.Font("Courier New", 0, 12));
        getContentPane().add(BoundTextField2);
        BoundTextField2.setBounds(460, 230, 240, 24);

        /* BoundTextField3 */
        BoundTextField3 = new javax.swing.JTextField();
        BoundTextField3.setFont(new java.awt.Font("Courier New", 0, 12));
        getContentPane().add(BoundTextField3);
        BoundTextField3.setBounds(460, 250, 240, 24);

        /* BoundTextField4 */
        BoundTextField4 = new javax.swing.JTextField();
        BoundTextField4.setFont(new java.awt.Font("Courier New", 0, 12));
        getContentPane().add(BoundTextField4);
        BoundTextField4.setBounds(460, 270, 240, 24);

        /* ContraintLabel1 */
        ContraintLabel1 = new javax.swing.JLabel();
        ContraintLabel1.setText("<= 0");
        getContentPane().add(ContraintLabel1);
        ContraintLabel1.setBounds(710, 120, 50, 20);

        /* ContraintLabel2 */
        ContraintLabel2 = new javax.swing.JLabel();
        ContraintLabel2.setText("<= 0");
        getContentPane().add(ContraintLabel2);
        ContraintLabel2.setBounds(710, 180, 34, 20);

        /* ContraintLabel3 */
        ContraintLabel3 = new javax.swing.JLabel();
        ContraintLabel3.setText("<= 0");
        getContentPane().add(ContraintLabel3);
        ContraintLabel3.setBounds(710, 160, 40, 20);

        /* ContraintLabel4 */
        ContraintLabel4 = new javax.swing.JLabel();
        ContraintLabel4.setText("<= 0");
        getContentPane().add(ContraintLabel4);
        ContraintLabel4.setBounds(710, 140, 40, 20);

        /* BoundLabel */
        BoundLabel1 = new javax.swing.JLabel();
        BoundLabel2 = new javax.swing.JLabel();
        BoundLabel3 = new javax.swing.JLabel();
        BoundLabel4 = new javax.swing.JLabel();
 
        /* GraphPanel */
        GraphPanel = new javax.swing.JPanel();
        GraphPanel.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        GraphPanel.setAutoscrolls(true);
        GraphPanel.setLayout(null);
        getContentPane().add(GraphPanel);
        GraphPanel.setBounds(20, 300, 430, 190);

        /* FitnessTextField */
        FitnessTextField = new java.awt.TextField();
        FitnessTextField_old = new javax.swing.JTextField();

        /************************************/
        
        BoundLabel1.setText("= 0");
        getContentPane().add(BoundLabel1);
        BoundLabel1.setBounds(710, 210, 30, 20);

        BoundLabel2.setText("= 0");
        getContentPane().add(BoundLabel2);
        BoundLabel2.setBounds(710, 230, 30, 20);

        BoundLabel3.setText("= 0");
        getContentPane().add(BoundLabel3);
        BoundLabel3.setBounds(710, 250, 30, 20);

        BoundLabel4.setText("= 0");
        getContentPane().add(BoundLabel4);
        BoundLabel4.setBounds(710, 270, 30, 20);

        getContentPane().add(FitnessTextField);
        FitnessTextField.setBounds(460, 300, 240, 90);

        FitnessTextField_old.setFont(new java.awt.Font("Courier New", 0, 12)); // NOI18N
        FitnessTextField_old.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                FitnessTextField_oldActionPerformed(evt);
            }
        });
        getContentPane().add(FitnessTextField_old);
        FitnessTextField_old.setBounds(460, 400, 240, 90);
        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void geneCheckBoxActionPerformed(java.awt.event.ActionEvent evt, Gene gene) {//GEN-FIRST:event_VarCheckBoxActionPerformed
        if(VarCheckBox.isSelected()){
            BNFMap.add(gene);
            System.out.println("Add " + gene.getClass().getSimpleName());
        }
        else{
            System.out.println("Remove " + gene.getClass().getSimpleName());
            BNFMap.remove(gene);
        }
    }//GEN-LAST:event_VarCheckBoxActionPerformed
    private JCheckBox setGeneCheckBox(String geneName, final Gene gene, int x, int y, int xm, int ym) {
    	JCheckBox CheckBox = new javax.swing.JCheckBox();
        CheckBox.setFont(new java.awt.Font("Courier New", 0, 10));
        CheckBox.setText(geneName);
        CheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                geneCheckBoxActionPerformed(evt, gene);
            }
        });
        getContentPane().add(CheckBox);
        CheckBox.setBounds(x, y, xm, ym);
		return CheckBox;
	}
	private void fileCancelButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed

    }//GEN-LAST:event_jButton4ActionPerformed

    private void fileCloseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FermerActionPerformed

        FileClose.setVisible(true);
    }//GEN-LAST:event_FermerActionPerformed

    private void fileSaveAsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnregistrerSousActionPerformed

        FileSaveAs.setVisible(true);
    }//GEN-LAST:event_EnregistrerSousActionPerformed

    private void fileSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EnregistrerActionPerformed

    }//GEN-LAST:event_EnregistrerActionPerformed

    private void fileOpenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_OuvrirActionPerformed
    
        FileOpen.setVisible(true);
    }//GEN-LAST:event_OuvrirActionPerformed

    private void aboutAboutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AproposActionPerformed

    }//GEN-LAST:event_AproposActionPerformed

    private void GoButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_GoButtonActionPerformed
        displayFunction();
        (new WorldDarwinPrime()).run(this);
    }//GEN-LAST:event_GoButtonActionPerformed

    private void PreOpCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PreOpCheckBoxActionPerformed
    }//GEN-LAST:event_PreOpCheckBoxActionPerformed
    
    private void SqrtCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SqrtCheckBoxActionPerformed
        
    }//GEN-LAST:event_SqrtCheckBoxActionPerformed
    
    private void XCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_XCheckBoxActionPerformed
        
    }//GEN-LAST:event_XCheckBoxActionPerformed
    private void menuFileItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_FichierItemStateChanged
    }//GEN-LAST:event_FichierItemStateChanged
    private void menuNewItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_NouveauItemStateChanged
    }//GEN-LAST:event_NouveauItemStateChanged
    private void ExitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitButtonActionPerformed
        System.out.println("bye bye!");
        this.setDefaultCloseOperation ( JFrame.EXIT_ON_CLOSE );
        setVisible( false );
        //dispose();
        System.exit(0);  
    }//GEN-LAST:event_ExitButtonActionPerformed

    public void FillFitnessTextField(String str){
        FitnessTextField.setEditable(true);
        FitnessTextField.setText(FitnessTextField.getText()+"\n"+str);
    }

    private void FitnessTextField_oldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FitnessTextField_oldActionPerformed
    }//GEN-LAST:event_FitnessTextField_oldActionPerformed

    private void FunctionTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_FunctionTextFieldActionPerformed
    }//GEN-LAST:event_FunctionTextFieldActionPerformed
    
    public void addLineConvergence(int x[],int y[],int k){
        Graphics g = GraphPanel.getGraphics();
        g.clearRect(0, 0, k, k);
        g.drawPolyline(x,y,k);
    }
    
    private void displayFunction(){
        FillFitnessTextField("helloooooo!!!\n\n");
//        FitnessTextField.setText("Hello!!!\n\n");
        int x[]=new int[670];
        int y[]=new int[670];
        x[0]=0;y[0]=0;
        int k=670;
        for(int j=0;j<20;j++){
            for(int i=0;i<k;i++){
                x[i]=i;
                y[i]=(int)(30*Math.cos((j+1)*i*Math.PI/k)+50);
            }
        addLineConvergence(x,y,k);
        try {
        	Thread.currentThread();
        	Thread.sleep(100);
        }
        catch (InterruptedException e) {e.printStackTrace();}
        }
        FillFitnessTextField("!!!afterFunction!!!");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JCheckBox ACheckBox;
    private javax.swing.JMenu MenuAbout;
    private javax.swing.JFrame AboutDisplay;
    private javax.swing.JFrame AboutHelp;
    private javax.swing.JFrame AboutAbout;
    private javax.swing.JButton AddButton;
    private javax.swing.JMenuItem Display;
    private javax.swing.JMenuItem Help;
    private javax.swing.JMenuItem About;
    private javax.swing.JTextField AvalTextField;
    private javax.swing.JCheckBox BCheckBox;
    private javax.swing.JLabel BoundLabel1;
    private javax.swing.JLabel BoundLabel2;
    private javax.swing.JLabel BoundLabel3;
    private javax.swing.JLabel BoundLabel4;
    private javax.swing.JTextField BoundTextField1;
    private javax.swing.JTextField BoundTextField2;
    private javax.swing.JTextField BoundTextField3;
    private javax.swing.JTextField BoundTextField4;
    private javax.swing.JTextField BvalTextField;
    private javax.swing.JCheckBox CCheckBox;
    private javax.swing.JLabel ContraintLabel1;
    private javax.swing.JLabel ContraintLabel2;
    private javax.swing.JLabel ContraintLabel3;
    private javax.swing.JLabel ContraintLabel4;
    private javax.swing.JTextField ContraintTextField1;
    private javax.swing.JTextField ContraintTextField2;
    private javax.swing.JTextField ContraintTextField3;
    private javax.swing.JTextField ContraintTextField4;
    private javax.swing.JTextField CvalTextField;
    private javax.swing.JCheckBox DCheckBox;
    private javax.swing.JButton DelButton;
    private javax.swing.JCheckBox DivideCheckBox;
    private javax.swing.JTextField DvalTextField;
    private javax.swing.JCheckBox ECheckBox;
    private javax.swing.JMenuItem Save;
    private javax.swing.JMenuItem SaveAs;
    private javax.swing.JTextField EvalTextField;
    private javax.swing.JToggleButton ExitButton;
    private javax.swing.JCheckBox ExpCheckBox;
    private javax.swing.JCheckBox ExpOpCheckBox;
    private javax.swing.JMenuItem Close;
    private javax.swing.JMenu MenuFile;
    private javax.swing.JFrame FileSaveAs;
    private javax.swing.JFrame FileClose;
    private javax.swing.JFrame FileOpen;
    private javax.swing.JFileChooser FileOpenChooser;
    private java.awt.TextField FitnessTextField;
    private javax.swing.JTextField FitnessTextField_old;
    private javax.swing.JTextField FunctionTextField;
    private javax.swing.JButton GoButton;
    private javax.swing.JPanel GraphPanel;
    private javax.swing.JCheckBox LogCheckBox;
    private javax.swing.JMenuBar MenuBar;
    private javax.swing.JCheckBox MinusCheckBox;
    private javax.swing.JCheckBox MultiplyCheckBox;
    private javax.swing.JMenuItem NewCorre;
    private javax.swing.JMenuItem NewEDP;
    private javax.swing.JMenuItem NewOpti;
    private javax.swing.JMenu MenuNew;
    private javax.swing.JFrame NewCorrelation;
    private javax.swing.JFrame NewPDE;
    private javax.swing.JFrame NewOptimisation;
    private javax.swing.JCheckBox OneCheckBox;
    private javax.swing.JMenuItem Open;
    private javax.swing.JMenuItem ParamGene;
    private javax.swing.JMenuItem ParamPopu;
    private javax.swing.JMenu MenuParameter;
    private javax.swing.JFrame ParameterGenetic;
    private javax.swing.JFrame ParameterPopulation;
    private javax.swing.JCheckBox PlusCheckBox;
    private javax.swing.JCheckBox PowerCheckBox;
    private javax.swing.JCheckBox PreOpCheckBox;
    private javax.swing.JCheckBox PreVarCheckBox;
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JMenuItem Publish;
    private javax.swing.JCheckBox SinCheckBox;
    private javax.swing.JCheckBox SqrtCheckBox;
    private javax.swing.JCheckBox TanCheckBox;
    private javax.swing.JCheckBox TenthCheckBox;
    private javax.swing.JCheckBox VarCheckBox;
    private javax.swing.JCheckBox VarOpCheckBox;
    private javax.swing.JCheckBox XCheckBox;
    private javax.swing.JTextField XmaxTextField;
    private javax.swing.JTextField XminTextField;
    private javax.swing.JCheckBox YCheckBox;
    private javax.swing.JTextField YmaxTextField;
    private javax.swing.JTextField YminTextField;
    private javax.swing.JCheckBox ZCheckBox;
    private javax.swing.JTextField ZmaxTextField;
    private javax.swing.JTextField ZminTextField;
    private javax.swing.JButton CloseButton;
    private javax.swing.JButton SaveButton;
    private javax.swing.JButton CancelButton;
    private javax.swing.JComboBox UnknownComboBox;
    private javax.swing.JFileChooser FileChooserSaveAs;
    private javax.swing.JTable UnknownTable;
    // End of variables declaration//GEN-END:variables

    /**
     * @param args the command line arguments
     */
    public void main() {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Gui().setVisible(true);
            }
        });
    }
}
